/**
 *
 *  @file task_id.hpp
 *  @author Gaspard Kirira
 *
 *  Copyright 2026, Gaspard Kirira.
 *  All rights reserved.
 *  https://github.com/cgride/graph
 *
 *  Use of this source code is governed by a MIT license
 *  that can be found in the LICENSE file.
 *
 *  Cgride
 *
 */
#ifndef CGRIDE_GRAPH_TASK_ID_HPP
#define CGRIDE_GRAPH_TASK_ID_HPP

#include <cstddef>
#include <string>
#include <string_view>

namespace cgride::graph
{
  /**
   * @class TaskId
   * @brief Stable identifier for a graph task.
   *
   * TaskId is intentionally small and string-backed so build tasks can be
   * identified by deterministic names generated by higher-level modules.
   */
  class TaskId
  {
  public:
    /**
     * @brief Construct an empty task id.
     */
    TaskId() = default;

    /**
     * @brief Construct a task id from a string.
     *
     * @param value Task id value.
     */
    explicit TaskId(std::string value);

    /**
     * @brief Create a task id from a string.
     *
     * @param value Task id value.
     * @return Task id.
     */
    [[nodiscard]] static TaskId from_string(std::string value);

    /**
     * @brief Access the task id value.
     */
    [[nodiscard]] const std::string &value() const noexcept;

    /**
     * @brief Return true when the task id is empty.
     */
    [[nodiscard]] bool empty() const noexcept;

    /**
     * @brief Return true when the task id is usable.
     */
    [[nodiscard]] bool valid() const noexcept;

    /**
     * @brief Compare two task ids.
     */
    friend bool operator==(const TaskId &lhs,
                                         const TaskId &rhs) noexcept;

    /**
     * @brief Compare two task ids.
     */
    friend bool operator!=(const TaskId &lhs,
                                         const TaskId &rhs) noexcept;

    /**
     * @brief Order task ids by value.
     */
    friend bool operator<(const TaskId &lhs,
                                        const TaskId &rhs) noexcept;

  private:
    std::string value_{};
  };

  /**
   * @brief Return the string value of a task id.
   *
   * @param id Task id.
   * @return Task id string.
   */
  [[nodiscard]] std::string_view to_string(const TaskId &id) noexcept;

  /**
   * @struct TaskIdHash
   * @brief Hash functor for TaskId.
   */
  struct TaskIdHash
  {
    /**
     * @brief Hash a task id.
     *
     * @param id Task id.
     * @return Hash value.
     */
    [[nodiscard]] std::size_t operator()(const TaskId &id) const noexcept;
  };

} // namespace cgride::graph

#endif // CGRIDE_GRAPH_TASK_ID_HPP
